save                : false
saveDir             : "/scratch2/users/rserage/"
publish_dir_mode    : "copy"
trainOnly           : true
testOnly            : false
train_data          : "/scratch2/users/rserage/Zoonosis*"